microsoft/ifc-spec

ltx/decls.tex

Add the missing `type` field of the structure of a `DeclSort::Template`.
Correct a few typos while in the neighborhood.
Fixes #8

Missing type field in DeclSort::Tempate

---

ltx/types.tex

The field `elaboration` was missing.
Fixes #13

Fix `TypeSort::Placeholder` description

---

ltx/types.tex

was missing from the `TypeBasis` member list.
Fixes #14

`TypeBasis::Concept`

---

ltx/exprs.tex

The `const.f64` partition was documented as an array of 64-bit floating point values.  However, the MSVC compiler  did emit array of 12-byte values.
Fixes #15

Clarify const.f64

---

ltx/decls.tex

The current spec lacks recording of `final` class types.  That causes unwarranted warning from compilers (MSVC).  This gap is now closed by recording `final` on scope types.

Add `final` trait for class types

---

ltx/words.tex

In the context of MSVC capturing templated expressions as sentences (sequence of words), clarify when operators are bound to declarations in the parsing context.  Same for `new` keyword.

Clarify bindings of operators and keywords in templated expressions

---

ltx/exprs.tex

Describe representation of the scope resolution operator `::` as monadic and dyadic operators.

Describe scope resolution

---

.github/workflows/produce-branch-pdf.yml
.github/workflows/produce-prerelease.yaml
.github/workflows/produce-release-branch.yml
.github/workflows/produce-release-pdf.yml

This change enables automatic PDF generation for releases when release
branches are changed. This supports backporting changes to prior
releases.
This works by:
- Creating a branch named `release/XYZ`, where XYZ is the name of a
release, when a release is made.
- Activating PDF generation when `release/XYZ` branches are changed.
- Updating the release XYZ when PDF generation is finished.
The release may be named anything. The only portion of the name that is
important for these actions is `release/` in the branch name.
The generated PDFs will be accessible from the Release pages and the links
to these PDFs are stable.
No manual work needs to be done beyond creating a release. All other steps
should happen automatically as normal development happens.

feat: update releases when release branches change

---

ltx/exprs.tex
ltx/ifc.tex

In preparation for gradual removal of parse trees, and more faithful representation of C++ semantics, the IFC ought to record the semantic resolution of operators used in monadic, dyadic, and triadic trees.

Add operator semantic resolution

---

ltx/exprs.tex

Cameron DaCamara pointed to me that MSVC still has problems with making the semantic resolution of operator of type `DeclIndex` (because reasons).  This patch temporarily make them of type `ExprIndex` until the MSVC reasons are resolved (soon hopefully)

Temporarily make operator semantic resolution an expression

---

ltx/exprs.tex

_new-expression_ and _delete-expression_ are now emitted using general structures.

Remove `new` and `delete` structures

---

ltx/exprs.tex

Reverts microsoft/ifc-spec#29.  The bindings should be declarations, not expressions referencing the declarations.

Revert "Temporarily make operator semantic resolution an expression"

---

ltx/decls.tex

This is a proposal to remove the `pack` field from the `DeclSort::Parameter` structure.

Remove `pack` from `DeclSort::Parameter`

---

ltx/exprs.tex

The fields denoting the type of an expression designating an object of class  is _TypeIndex_, not _DeclIndex_.

Fix thinkos in class type object expression description

---

ltx/exprs.tex

The fields denoting the type of an expression designating an object of class  is _TypeIndex_, not _DeclIndex_.

Fix thinkos in class type object expression description (#36)

---

ltx/exprs.tex

Add missing description for saturated arithmetic mode on the MSVC toolset

Saturated Arithmetic

---

ltx/exprs.tex
ltx/ifc-format.sty
ltx/stmts.tex

The `StmtSort` hierarchy went through a face lift in MSVC, leading to version 0.42

Document new `StmtSort`

---

ltx/parse.tex

The commit #60 was missing the padding bytes at the end of the structure.

Padding bytes in `SyntaxSort::FunctionDeclarator`

---

ltx/exprs.tex

The components are NOT restricted to `ExprSort::UnqualifiedId`.
Fix #70

Clarify `ExprtSort::QualifiedName`

---

ltx/decls.tex
ltx/exprs.tex
ltx/stmts.tex

Add `DeclSort::DefaultArgument` to represent default arguments -- they are notionally declarations subject to the ODR, for all practical purposes.

Add structure for default arguments

---

ltx/exprs.tex

Document an MSVC-builtin for annotating runtime allocated object address with the dynamic type of the allocated object

DyadicOperator::MsvcBuiltinAllocationAnnotation

---

ltx/exprs.tex

Fix `ExprSort::TemplateReference` structure

---

ltx/decls.tex
ltx/directives.tex
ltx/exprs.tex
ltx/heaps.tex
ltx/ifc.tex
ltx/stmts.tex

to classify grammatical declarations that modify the behavior of a C++ translator

Introduce Directive Hierarchy

---

ltx/decls.tex
ltx/types.tex

The `initializer` field of a `DeclSort::Parameter` structure is an `ExprIndex` abstract reference pointing (when not null) to trees with specific shapes (a `ExprSort::NamedDecl` that references a `DeclSort::DefaultArgument`).
Fix #102

Update `DeclSort::Parameter` initializer

---

ltx/traits.tex

This patch partially resolves the need for storing the hash of the content of a source file as described in #138 .

MSVC source file hash algorithms

---

ltx/exprs.tex

And also clarify the structure of cast expressions and relationships to dyadic operators.
Fixes #162

Document array decay and function decay

---

ltx/decls.tex

Define `FunctionTraits::ExplicitObjectParameter` for member-functions with an explicit object parameter.
Fixes #159

Explicit object parameter member function trait
